# Generated by Django 2.2.7 on 2019-11-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=255)),
                ('temp', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
            ],
        ),
    ]
